### ISSUE TITLE
Flowchart for search attribute

### ISSUE THREAD

**Issue by az0** [bleachbit/docs#4]
@Tobias-B-Besemer

Is this flowchart helpful? (Click to expand image)

![flowchart](https://user-images.githubusercontent.com/933680/54658361-ae368500-4a92-11e9-9118-25c5e2ccc4c3.png)

Graphviz code
````
digraph G {

  
  delete_a_single_file[label="Delete a single file or empty directory with literal name?"]
  delete_a_single_file->"Use search=file" [label=yes]
  delete_a_single_file->pattern_one_dir[label=no]
  pattern_one_dir->"Use search=glob"[label=yes]
  pattern_one_dir[label="Delete files matching pattern without recursion into sub-directories?"]
  pattern_one_dir->delete_all_under_dir[label=no]
  delete_all_under_dir[label="Recurse into one or more directories and delete all files and folders?"]
  delete_all_under_dir->search_walk_all[label="yes"]
  search_walk_all[label="Use search=walk.all"]
  delete_all_under_dir->delete_file_under_dir[label="no"]
  delete_file_under_dir[label="Recurse into one or more directories and delete only files?"]
  delete_file_under_dir->"Use search=walk.file"[label=yes]
  delete_file_under_dir->"????"[label=no]
}
````

**Comment by Tobias-B-Besemer** [comment]
Even if it looks different, I did understand it so far... ;-)

...but I still have some questions to the wildcards...
...I asked them in a PR - don't know anymore which one it was - but you will find it, if you work up my PRs... ;-)

**Comment by Tobias-B-Besemer** [comment]
I will make a table with how I understood it, then we see, if I really understand... ;-)

**Comment by Tobias-B-Besemer** [comment]
<H1>Deletion use cases</H1>

**Delete Files**

| Single file? | Recursive? | "*"/"?" used in path or filename? | Use: |
| --- | --- | --- | --- |
| Yes | - | No | search="file" |
| Yes | - | Yes | search="glob" |
| No | No | Path=No | search="glob" |
| No | No | Path=Yes | search="glob" |
| No | Yes | Path=No | search="walk.files" with regex="[...]" |
| No | Yes | Path=Yes | search="walk.files" with regex="[...]" |

<br>

**Delete Folders**

| What to delete? | "*"/"?" used in path or folder-name? | Use: |
| --- | --- | --- |
| Folder content, recursive, without sub-folders (structure) | No | search="walk.files" |
| Folder content, recursive, without sub-folders (structure) | Yes | search="walk.files" |
| Folder content, recursive, with sub-folders (structure) | No | search="walk.all" |
| Folder content, recursive, with sub-folders (structure) | Yes | search="walk.all" |
| Folder content, not recursive, without sub-folders | No | search="glob" |
| Folder content, not recursive, without sub-folders | Yes | search="glob" |
| Folder empty | No | search="file" |
| Folder empty | Yes | search="glob" |
| Folder not empty | No | search="folder" (*1) |
| Folder not empty | No | search="walk.all" and the search="file" |
| Folder not empty | Yes | search="folder" (*1) |
| Folder not empty | Yes | search="walk.all" and then search="glob" |

*1: Not yet implemented!

**Comment by Tobias-B-Besemer** [comment]
@az0, are these tables correct ???

Can I add them to the new CleanerML docu ???

**Comment by Tobias-B-Besemer** [comment]
Finally I added the table to the new CleanerML docu... (...I still hope the table is right...)
